name: Aggiorna README con elenco articoli

on:
  push:
    paths:
      - 'articoli/*.md'
      - 'update_readme.py'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Esegui script aggiornamento README
        run: python update_readme.py

      - name: Debug git status e remoti
        run: |
          git status
          git remote -v
          git branch -vv

      - name: Commit e push se ci sono modifiche
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if ! git diff --cached --quiet; then
            git commit -m "Aggiorna README.md con elenco articoli"
            git push
          else
            echo "Nessuna modifica da committare."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
